# Generated by Django 4.0.4 on 2022-04-27 14:07

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('editor', models.IntegerField(blank=True, null=True)),
                ('time_flag', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
