# Generated by Django 4.0.3 on 2022-03-21 14:17

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_quill.fields.QuillField()),
                ('date_created', models.DateTimeField(blank=True)),
                ('date_uploaded', models.DateTimeField(blank=True)),
                ('if_uploaded', models.BooleanField(blank=True)),
            ],
        ),
    ]
