# Generated by Django 4.0.3 on 2022-03-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='in_progress',
            field=models.IntegerField(),
        ),
    ]
