# Generated by Django 4.0.4 on 2022-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_creation', '0002_article_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='time_flag',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
