# Generated by Django 4.0.3 on 2022-04-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_preview', models.CharField(max_length=200)),
                ('card_title', models.CharField(max_length=60)),
                ('card_description', models.CharField(max_length=150)),
                ('last_updated', models.CharField(max_length=30)),
            ],
        ),
    ]
