# Generated by Django 4.0.4 on 2022-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='')),
                ('is_article', models.BooleanField(editable=False)),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
