# Generated by Django 4.0.2 on 2022-02-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0002_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('date_created', models.DateField()),
                ('date_uploaded', models.DateField(blank=True)),
                ('preview_image', models.ImageField(blank=True, upload_to='preview')),
                ('preview_text', models.CharField(blank=True, max_length=300)),
                ('content_empty', models.BooleanField()),
                ('article_content', models.TextField(blank=True)),
            ],
        ),
    ]
