# Generated by Django 4.0.4 on 2022-05-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_parent_id_comment_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='artcile',
            new_name='article',
        ),
    ]
