# Generated by Django 4.0.2 on 2022-02-21 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GraduationYear', models.IntegerField()),
                ('Letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('User_main', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('n', 'neutral')], max_length=1)),
                ('isConfirmed', models.BooleanField()),
                ('BIO', models.CharField(max_length=570)),
                ('Birthday', models.DateField(blank=True)),
                ('mediaPost', models.IntegerField()),
                ('city', models.IntegerField()),
                ('Class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Class', to='user_profile.grade')),
                ('Position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Position', to='user_profile.position')),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Subject', to='user_profile.subject')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='Specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Specializations', to='user_profile.specialization'),
        ),
    ]
