# Generated by Django 4.0.2 on 2022-02-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Position',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='User_main',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
